travis:
  secure:
    BINSTAR_TOKEN: KNIefePwpZZbIdvv6jYL5dzevs/Q/gGrGoEIO1dJ3TIWhkbWxQvWPwYg43fwB2684hMPba4d0i90x9XErj18zB2oF3qz3X8xPJWwM6+V6z6Snwm4KPgdwT7CCPvJlMfeuFK/WYTITUN4mioUxmcQMMfEcxcpRFN9lN4ZZcTX0epM5rn+Sjo5YvINOIJpjorsCbOiSHZFwHgCbcsiToD6QnXsHBII/Sp9UtOd7zp/tQa+g0j2jRJAN3e+GAtoBNzoID4Rlw3rL3p+kSpAV8q9Rz5AZJND0Zhlw3SBmVNPUsNBJQcS08+1ck6XU3aDrVkuWUUDK+BKBNwKSwyQ0DwxoZUBTUSzEP70UNXsqQJ18kGsR9eOvK6uah/dkJq4wep9UXAeQpa4bXBWk6/3FNkaD5sU22DvVzFGnZXDQUj6dEHV9O0gSYlz7Al1ucyyOdQmfVx6eU+7SVFEB0GBui+cMMXwTuLfTgr2PUy5HsWe9/ft3nxuVMC209NR77oqyvF/jXV9ozIGkHYz04cqOoQ68bRITxks4GJ8LWddgk8N7D0cCwjky/t/dZGPxeD5NogNZ1J1OfGUKACbQ/uJr14RO7VWkJX7dCNIEnDechDyzjEIF43FVY8Ip8rDsnL5ocO0Jlp13ubVmZSwLjHqIb/zx+BNT8FSDA8mb/zg2TCm6Fs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
